name: Debug Deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install Shopify CLI
      run: |
        npm install -g @shopify/cli @shopify/theme
        shopify version
        
    - name: Debug Environment
      run: |
        echo "🔍 Environment Debug Info:"
        echo "Store: ${{ secrets.SHOPIFY_STORE }}"
        echo "Token length: ${#SHOPIFY_CLI_THEME_TOKEN}"
        echo "Token prefix: ${SHOPIFY_CLI_THEME_TOKEN:0:10}..."
        echo "Working directory: $(pwd)"
        echo "Files in directory:"
        ls -la
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        
    - name: Test Shopify Connection
      run: |
        echo "🔗 Testing Shopify connection..."
        shopify theme list --store="${{ secrets.SHOPIFY_STORE }}.myshopify.com" || echo "❌ Connection failed"
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        
    - name: Attempt Deployment with Verbose Output
      run: |
        echo "🚀 Attempting deployment with verbose output..."
        shopify theme push \
          --store="${{ secrets.SHOPIFY_STORE }}.myshopify.com" \
          --live \
          --force \
          --verbose \
          --json || echo "❌ Deployment failed"
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        
    - name: Alternative: Try Development Theme
      run: |
        echo "🧪 Trying development theme as fallback..."
        shopify theme push \
          --store="${{ secrets.SHOPIFY_STORE }}.myshopify.com" \
          --development \
          --force \
          --verbose \
          --json || echo "❌ Development deployment also failed"
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}