name: Shopify Theme Sync

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'assets/**'
      - 'config/**'
      - 'layout/**'
      - 'locales/**'
      - 'sections/**'
      - 'snippets/**'
      - 'templates/**'

jobs:
  sync-theme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
      
    - name: Validate theme structure
      run: |
        echo "🔍 Validating theme structure..."
        if [ ! -f "layout/theme.liquid" ]; then
          echo "❌ Missing layout/theme.liquid"
          exit 1
        fi
        if [ ! -f "config/settings_schema.json" ]; then
          echo "❌ Missing config/settings_schema.json" 
          exit 1
        fi
        echo "✅ Theme structure valid"
        
    - name: Deploy to Development Theme
      if: github.ref != 'refs/heads/main'
      run: |
        echo "🚀 Deploying to development theme..."
        shopify theme push --development --store=${{ secrets.SHOPIFY_STORE }} --path=. --ignore=README.md --ignore=.github
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
        
    - name: Deploy to Live Theme
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🎯 Deploying to LIVE theme..."
        shopify theme push --live --store=${{ secrets.SHOPIFY_STORE }} --path=. --ignore=README.md --ignore=.github
      env:
        SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
        
    - name: Success notification
      if: success()
      run: |
        echo "✅ Theme successfully deployed to Shopify!"
        echo "🔗 Store: https://${{ secrets.SHOPIFY_STORE }}.myshopify.com"
        
    - name: Failure notification  
      if: failure()
      run: |
        echo "❌ Theme deployment failed"
        echo "Check the logs above for details"